name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
  - title: 'Fixes'
    labels:
      - 'bug'
version-resolver:
  major:
    labels:
      - 'increase-major'
  minor:
    labels:
      - 'increase-minor'
  default: patch
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's new

  $CHANGES
